from django.contrib import admin
from django.urls import path
from users import views as user_views
from platformsite import views as platform_views
from course import views as course_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/category/<str:category_id>/', platform_views.CategoryView.as_view(), name='category_home'),
    path('home/vehicles/', platform_views.VehiclesView.as_view(), name='vehicles_home'),
    path('home/instructors/', platform_views.InstructorsView.as_view(), name='instructors_home'),
    path('home/theories/', platform_views.TheorysView.as_view(), name='theories_home'),
    path('login/', user_views.LoginView.as_view(), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('students/', course_views.StudentsView.as_view(), name='students'),
    path('students/<int:student_id>/edit', course_views.EditStudentView.as_view(), name='edit_student'),
    path('students/<int:student_id>/create_account', course_views.create_account_for_student_view, name='create_account_for_student'),
    path('students/<int:student_id>/delete_account', course_views.delete_account_of_student_view, name='delete_account_of_student'),
    path('students/<int:student_id>/generate_password', course_views.generate_new_password_for_student_view, name='generate_new_password_for_student'),
    path('students/<int:student_id>/courses/', course_views.CoursesView.as_view(), name='student_courses'),
    path('register_student/', course_views.RegisterStudentView.as_view(), name='register_student'),
    path('register_instructor/', course_views.RegisterInstructorView.as_view(), name='register_instructor'),
    path('register_employee/', course_views.RegisterEmployeeView.as_view(), name='register_employee'),
    path('upcoming_lessons/', course_views.UpcomingLessonsView.as_view(), name='upcoming_lessons'),
    path('profile_settings/', course_views.ProfileSettingsView.as_view(), name='profile_settings'),
    path('courses/', course_views.CoursesView.as_view(), name='courses'),
    path('courses/<int:course_id>/', course_views.CourseDetailView.as_view(), name='course_detail'),
    path('courses/create/', course_views.CreateCourseView.as_view(), name='create_course'),
    path('courses/create/<int:student_id>/', course_views.CreateCourseView.as_view(), name='create_course_for_student'),
    path('courses/<int:course_id>/edit/', course_views.EditCourseView.as_view(), name='edit_course'),
    path('practical/<int:practical_id>/', course_views.PracticalDetailView.as_view(), name='practical_detail'),
    path('practical/<int:practical_id>/change_status/', course_views.change_practical_lesson_status_view, name='change_practical_lesson_status'),
    path('practical/<int:practical_id>/edit/', course_views.EditPracticalLessonView.as_view(), name='edit_practical_lesson'),
    path('practical/<int:practical_id>/delete/', course_views.delete_practical_lesson_view, name='delete_practical_lesson'),
    path('practical/create/', course_views.CreatePracticalLessonView.as_view(), name='create_practical_lesson'),
    path('practical/create/<int:course_id>/', course_views.CreatePracticalLessonView.as_view(), name='create_practical_lesson_for_course'),
    path('theory/create', course_views.CreateTheoryView.as_view(), name='create_theory'),
    path('theory/<int:theory_id>/edit/', course_views.EditTheoryView.as_view(), name='edit_theory'),
    path('theory/<int:theory_id>/delete/', course_views.delete_theory_view, name='delete_theory'),
    path('theories/', course_views.TheoriesView.as_view(), name='theories'),
    path('vehicles/', course_views.VehiclesView.as_view(), name='vehicles'),
    path('vehicle/create/', course_views.CreateVehicleView.as_view(), name='create_vehicle'),
    path('vehicle/<int:vehicle_id>/delete/', course_views.delete_vehicle_view, name='delete_vehicle'),
    path('vehicle/<int:vehicle_id>/edit/', course_views.EditVehicleView.as_view(), name='edit_vehicle'),
    path('vehicle/<int:vehicle_id>/change_status', course_views.change_vehicle_availability_view, name='change_vehicle_availability'),
    path('categories/', course_views.CategoriesView.as_view(), name='categories'),
    path('category/create/', course_views.CreateCategoryView.as_view(), name='create_category'),
    path('category/<str:category_symbol>/edit/', course_views.EditCategoryView.as_view(), name='edit_category'),
    path('category/<str:category_symbol>/delete/', course_views.delete_category_view, name='delete_category'),
    path('category/<str:category_symbol>/change_status', course_views.change_category_availability_view, name='change_category_availability'),
    path('instructors/', course_views.InstructorsView.as_view(), name='instructors'),
    path('instructor/<int:instructor_id>/change_status/', course_views.change_instructor_availability_view, name='change_instructor_availability'),
    path('instructors/<int:instructor_id>/edit/', course_views.EditInstructorView.as_view(), name='edit_instructor'),
    path('instructors/<int:instructor_id>/delete/', course_views.delete_instructor_view, name='delete_instructor'),
    path('instructors/<int:instructor_id>/delete_account/', course_views.delete_account_of_instructor_view, name='delete_account_of_instructor'),
    path('instructors/<int:instructor_id>/generate_password/', course_views.generate_new_password_for_instructor_view, name='generate_new_password_for_instructor'),
    path('instructors/<int:instructor_id>/create_account/', course_views.create_account_for_instructor_view, name='create_account_for_instructor'),
    path('qualifications/<int:instructor_id>/', course_views.QualificationsView.as_view(), name='qualifications'),
    path('qualification/<int:instructor_id>/add/', course_views.CreateQualificationView.as_view(), name='create_qualification'),
    path('qualification/<int:qualification_id>/delete/', course_views.delete_qualification_view, name='delete_qualification'),
    path('employees/', course_views.EmployeesView.as_view(), name='employees'),
    path('employees/<int:employee_id>/edit', course_views.EditEmployeeView.as_view(), name='edit_employee'),
    path('employees/<int:employee_id>/delete', course_views.delete_employee_view, name='delete_employee'),
    path('employees/<int:employee_id>/delete_account', course_views.delete_account_of_employee_view, name='delete_account_of_employee'),
    path('employees/<int:employee_id>/generate_password', course_views.generate_new_password_for_employee_view, name='generate_new_password_for_employee'),
    path('employees/<int:employee_id>/create_account', course_views.create_account_for_employee_view, name='create_account_for_employee'),
    path('employees/<int:employee_id>/change_permissions', course_views.change_employee_permissions_type_view, name='change_employee_permissions_type'),
    path('', platform_views.HomeView.as_view(), name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "platformsite.views.page_not_found_view"   