# Generated by Django 4.2.1 on 2023-06-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_remove_category_required_practical_hours_gte_0_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('instructor', 'category')},
        ),
    ]
