# Generated by Django 4.2.1 on 2023-05-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('date_of_employment', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
