# Generated by Django 4.2.1 on 2023-06-19 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_qualification_date_of_achievement_lte_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2023, 6, 19))), name='employee_birth_date_lte_today'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('date_of_employment__lte', datetime.date(2023, 6, 19))), name='employee_date_of_employment_gte_birth_date'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2023, 6, 19))), name='instructor_birth_date_lte_today'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.CheckConstraint(check=models.Q(('date_of_employment__lte', datetime.date(2023, 6, 19))), name='instructor_date_of_employment_gte_birth_date'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2023, 6, 19))), name='student_birth_date_lte_today'),
        ),
    ]
