# Generated by Django 4.2.1 on 2023-06-22 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_instructor_instructor_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='employee_birth_date_lte_today',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='employee_date_of_employment_gte_birth_date',
        ),
        migrations.RemoveConstraint(
            model_name='instructor',
            name='instructor_birth_date_lte_today',
        ),
        migrations.RemoveConstraint(
            model_name='instructor',
            name='instructor_date_of_employment_gte_birth_date',
        ),
        migrations.RemoveConstraint(
            model_name='qualification',
            name='date_of_achievement_lte_today',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='student_birth_date_lte_today',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2023, 6, 22))), name='employee_birth_date_lte_today'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('date_of_employment__lte', datetime.date(2023, 6, 22))), name='employee_date_of_employment_gte_birth_date'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(check=models.Q(('date_of_achievement__lte', datetime.date(2023, 6, 22))), name='date_of_achievement_lte_today'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.date(2023, 6, 22))), name='student_birth_date_lte_today'),
        ),
    ]
