# Generated by Django 4.2.1 on 2023-05-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('symbol', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category_photos/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkk_number', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('course_status', models.CharField(choices=[('R', 'Rozpoczęty'), ('Z', 'Zakończony'), ('A', 'Anulowany')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('num_of_hours', models.IntegerField()),
                ('num_of_km', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('T', 'Tygodniowy'), ('W', 'Weekendowy')], default='T', max_length=1)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('SO', 'Samochód osobowy'), ('MO', 'Motocykl'), ('SC', 'Samochód ciężarowy'), ('BU', 'Autobus'), ('PL', 'Przyczepa lekka'), ('PC', 'Przyczepa ciężka')], default='SO', max_length=2)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_production', models.IntegerField(blank=True, null=True)),
                ('gearbox_type', models.CharField(choices=[('M', 'Manualna'), ('A', 'Automatyczna')], default='M', max_length=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
