# Generated by Django 4.2.1 on 2023-05-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('R', 'Rozpoczęty'), ('Z', 'Zakończony'), ('A', 'Anulowany')], default='R', max_length=1),
        ),
    ]
