# Generated by Django 4.2.1 on 2023-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default='default_vehicle.jpg', upload_to='vehicle_photos'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='default_category.jpg', upload_to='category_photos'),
        ),
    ]
