# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_vehicle_photo_alter_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='photo',
        ),
    ]
