# Generated by Django 4.2.1 on 2023-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_practicallesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('SO', 'Samochód osobowy'), ('MO', 'Motocykl'), ('SC', 'Samochód ciężarowy'), ('BU', 'Autobus'), ('PL', 'Przyczepa lekka'), ('PC', 'Przyczepa ciężka')], default='SO', max_length=2)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_production', models.IntegerField(blank=True, null=True)),
                ('gearbox_type', models.CharField(choices=[('M', 'Manualna'), ('A', 'Automatyczna')], default='M', max_length=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
