# Generated by Django 4.2.1 on 2023-05-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicallesson',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.vehicle'),
        ),
    ]
