# Generated by Django 4.2.1 on 2023-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='required_practical_hours',
            field=models.IntegerField(default=0),
        ),
    ]
