# Generated by Django 4.2.1 on 2023-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_category_required_practical_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorycourse',
            name='start_date',
            field=models.DateField(unique_for_date='start_date'),
        ),
    ]
