# Generated by Django 4.2.1 on 2023-06-03 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_theorycourse_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorycourse',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='theorycourse',
            unique_together={('type', 'start_date')},
        ),
        migrations.AddConstraint(
            model_name='theorycourse',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2023, 6, 4))), name='start_date_gte_today'),
        ),
    ]
