# Generated by Django 4.2.1 on 2023-06-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_theorycourse_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='theorycourse',
            name='start_date_gte_today',
        ),
    ]
