# Generated by Django 4.2.1 on 2023-06-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_theorycourse_start_date_gte_today'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theorycourse',
            unique_together=set(),
        ),
    ]
