# Generated by Django 4.2.1 on 2023-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_theorycourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theorycourse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('required_practical_hours__gte', 0)), name='required_practical_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('discount_price__gte', 0)), name='discount_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', models.F('discount_price'))), name='price_gte_discount_price'),
        ),
    ]
