# Generated by Django 4.2.1 on 2023-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_theorycourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('discount_price__isnull', False), ('is_discount', True)), name='is_discount_true_discount_price_not_null'),
        ),
    ]
