# Generated by Django 4.2.1 on 2023-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_category_is_discount_true_discount_price_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='is_discount_true_discount_price_not_null',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_discount', True), ('discount_price__isnull', False)), ('is_discount', False), _connector='OR'), name='is_discount_true_discount_price_not_null'),
        ),
    ]
