# Generated by Django 4.2.1 on 2023-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_category_is_discount_true_discount_price_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='price_gte_discount_price',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', models.F('discount_price'))), name='price_gte_discount_price'),
        ),
    ]
