# Generated by Django 4.2.1 on 2023-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_remove_category_price_gte_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='required_practical_hours_gte_0',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('required_practical_hours__gt', 0)), name='required_practical_hours_gte_0'),
        ),
    ]
