# Generated by Django 4.2.1 on 2023-06-05 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_remove_category_required_practical_hours_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='theorycourse',
            name='start_date_gte_today',
        ),
        migrations.AddConstraint(
            model_name='theorycourse',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2023, 6, 5))), name='start_date_gte_today'),
        ),
    ]
