# Generated by Django 4.2.1 on 2023-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_remove_theorycourse_start_date_gte_today_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='practicallesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('date', 'start_time', 'instructor'), name='unique_practical_lesson'),
        ),
    ]
