# Generated by Django 4.2.1 on 2023-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_practicallesson_unique_practical_lesson'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='theorycourse',
            name='start_date_gte_today',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('cost__gte', 0)), name='course_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='practicallesson',
            constraint=models.CheckConstraint(check=models.Q(('num_of_hours__gt', 0)), name='num_of_hours_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='practicallesson',
            constraint=models.CheckConstraint(check=models.Q(('num_of_km__gt', 0)), name='num_of_km_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='practicallesson',
            constraint=models.CheckConstraint(check=models.Q(('cost__gt', 0)), name='practical_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('year_of_production__gte', 1900)), name='year_gte_1900'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('year_of_production__lte', 2023)), name='year_lte_current_year'),
        ),
    ]
