# Generated by Django 4.2.1 on 2023-06-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_theorycourse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theorycourse',
            unique_together=set(),
        ),
    ]
