# Generated by Django 4.2.1 on 2023-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_alter_theorycourse_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='year_lte_current_year',
        ),
    ]
